title: Muhamad Munaji
logo: "https://drive.google.com/file/d/1Q3IYfI-udyw5p7Q5cz0vUlf2cPh56Npk/view?usp=sharing"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mathematical Education 
  <br><br>
  Universitas Sultan Ageng Tirtayasa 
  <br><br>
  Data Warehousing, Analysis, and Visualization for Business Insights
  <br><br>
  PZSIB
  <br><br>
  <a href="https://www.linkedin.com/in/muhamad-munaji-ba374322a">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
